# host, p6-ad-sign.byteimg.com, reject
# host, p9-ad-sign.byteimg.com, reject
host-keyword, -ad-sign.byteimg.com, reject
host-keyword, -novel.byteimg.com, reject

# host, i.snssdk.com, reject
# host, i-lq.snssdk.com, reject
host, is.snssdk.com, reject
host, mcs.snssdk.com, reject
host, vas-lf-x.snssdk.com, reject
host, tnc3-alisc1.snssdk.com, reject
host, security-lq.snssdk.com, reject
host, tnc3-aliec2.snssdk.com, reject

# host-suffix, zijieapi.com, reject
# host, ma.zijieapi.com, reject
host, mon.zijieapi.com, reject
host, timon.zijieapi.com, reject
host, feedback-c.zijieapi.com, reject
host, polaris-sinfonlineb.zijieapi.com, reject
host-keyword, -lf.zijieapi.com, reject
host-keyword, -hl.zijieapi.com, reject

host, dig.bdurl.net, reject
host, activity-ag.awemeughun.com, reject
host, msync-im1-vip6-std.easemob.com, reject
host, apd-pcdnwxlogin.teg.tencent-cloud.net, reject

host, api.iegadp.qq.com, reject
host, *default.ixigua.com, reject
host, sf3-ttcdn-tos.pstatp.com, reject

host, *novelapp.ixigua.com, reject
host, v6-novelapp.ixigua.com, reject
host, v6-novelapp.fqnovelvod.com, reject

host-suffix, pglstatp-toutiao.com, reject
host-suffix, pangolin-sdk-toutiao-b.com, reject
host-suffix, pangolin-sdk-toutiao.com, reject
host-suffix, pangolin-sdk-toutiao1.com, reject

# host-suffix, byteorge.com, reject
# host-suffix, bytegoofy.com, reject
# host-suffix, bytedance.com, reject
