host, cdn-new-ad.wtzw.com, reject
host, a-remad.qm989.com, reject
host, mobads.baidu.com, reject
host, qzs.gdtimg.com, reject
host, mobads-pre-config.cdn.bcebos.com, reject
host, pgdt.ugdtimg.com, reject

host, dsp-x.jd.com, reject
host, api-cfg.wtzw.com, reject
host, p1-lm.adukwai.com, reject
host, open.e.kuaishou.cn, reject

host-suffix, gdt.qq.com, reject
host-keyword, remad.qm989.com, reject

# host, lf-cdn-tos.bytescm.com, reject
# host-suffix, pglstatp-toutiao.com, reject
# host-suffix, pangolin-sdk-toutiao-b.com, reject
# host-suffix, pangolin-sdk-toutiao.com, reject
# host-suffix, pangolin-sdk-toutiao1.com, reject
